#spring.application.name=dubbo-consumer
#http://localhost:8102/auth/consumer/branch
server: 
  context-path: /auth
  port: 8102
#应用名称
spring: 
  dubbo:
    application:
      name: auth-consumer
#注册中心地址
    protocol:
      name: dubbo
    registry:
      address: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2180,127.0.0.1:2182
#调用dubbo组建扫描的项目路径
    scan: com.demo.controller
